import { AppProps } from 'next/app';
import Head from 'next/head';
import '../styles/globals.scss';
import { LangProvider } from '@/lang/LangProvider';

const MyApp = ({ Component, pageProps }: AppProps) => {
    const appName = process.env.NEXT_PUBLIC_APP_NAME || 'Default App Name';
    return (
        <>
            <Head>
                <title>{appName}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <LangProvider>
                <Component {...pageProps} />
            </LangProvider>
        </>
    );
}

export default MyApp;
